name: CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  dotnet-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x
      - name: Install MAUI workload
        run: dotnet workload install maui
      - name: Build
        run: dotnet build RockPaperScissorsClient/RockPaperScissorsClient.csproj -c Release -f:net8.0-windows10.0.19041.0
        working-directory: RockPaperScissors/RockPaperScissorsClient

  # Job for compiling the Arduino project
  arduino-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@v1
      with:
        version: '0.19.2'

    - name: Install Arduino AVR platform
      run: arduino-cli core install arduino:avr

    - name: Install Required Libraries
      run: arduino-cli lib install "ArduinoUnit"

    - name: Build Arduino Project
      run: arduino-cli compile --fqbn arduino:avr:uno RockPaperScissors/RockPaperScissorsServer/RockPaperScissorsServer.ino

    - name: Upload Arduino Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: arduino-build
        path: RockPaperScissors/RockPaperScissorsServer/build/*
